[package]
name = "rsfbclient"
description = "Binds to official firebird client lib"
version = "0.4.0"
authors = ["Luis Fernando Batels <luisfbatels@gmail.com>", "Jairo H Wiethan <jairinhowiethan@gmail.com>"]
edition = "2018"
repository = "https://github.com/fernandobatels/rsfbclient"
keywords = ["firebird", "fbclient", "database", "ffi"]
categories = ["database"]
license = "MIT"
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytes = "0.5"
chrono = { version = "0.4", optional = true }
libc = "0.2"
libloading = { version = "0.6", optional = true }
lru-cache = "0.1"
num_enum = "0.5.0"
once_cell = { version = "1.4", optional = true }
pwhash = "0.3"
r2d2 = { version = "0.8", optional = true }
thiserror = "1.0"

[features]
default = ["date_time", "pool"]
date_time = ["chrono"]
dynamic_loading = ["libloading", "once_cell"]
pool = ["r2d2"]
