[package]
name = "rsfbclient"
description = "Binds to official firebird client lib"
version = "0.4.0"
authors = ["Luis Fernando Batels <luisfbatels@gmail.com>", "Jairo H Wiethan <jairinhowiethan@gmail.com>"]
edition = "2018"
repository = "https://github.com/fernandobatels/rsfbclient"
keywords = ["firebird", "fbclient", "database", "ffi"]
categories = ["database"]
license = "MIT"
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytes = "0.5"
chrono = { version = "0.4", optional = true }
digest = "0.9.0"
generic-array = "0.14.3"
hex = "0.4.2"
lazy_static = "1.4.0"
lru-cache = "0.1"
num-bigint = "0.3.0"
num_enum = "0.5.1"
pwhash = "0.3"
r2d2 = { version = "0.8", optional = true }
rand = "0.7.3"
sha-1 = "0.9.1"
thiserror = "1.0"

[features]
default = ["date_time", "pool"]
date_time = ["chrono"]
pool = ["r2d2"]
