[package]
name = "rsfbclient"
description = "Binds to official firebird client lib"
version = "0.1.1"
authors = ["Luis Fernando Batels <luisfbatels@gmail.com>", "Jairo H Wiethan <jairinhowiethan@gmail.com>"]
edition = "2018"
repository = "https://github.com/fernandobatels/rsfbclient"
keywords = ["firebird", "fbclient", "database", "ffi"]
categories = ["database"]
license = "MIT"
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = { version = "0.4", optional = true }
lazy_static = { version = "1.4", optional = true }
libc = "0.2"
libloading = { version = "0.6", optional = true }
once_cell = { version = "1.4", optional = true }

[features]
default = ["date_time"]
date_time = ["chrono"]
dynamic_loading = ["libloading", "lazy_static", "once_cell"]
